[repository]
name = "csd-minimize"
authors = ["ar-Raqmi"]

[csd-minimize]
description = "Configurable Client-Side Decoration (CSD) minimize button handler"
authors = ["ar-Raqmi"]
output = "csd-minimize.so"
build = ["make"]
